CREATE TABLE IF NOT EXISTS users
(
id BIGSERIAL PRIMARY KEY,
username	VARCHAR(64) NOT NULL UNIQUE,
first_name	VARCHAR(96) DEFAULT '',
last_name	VARCHAR(96) DEFAULT '',
email	VARCHAR(96) DEFAULT '' UNIQUE,
date_joined	VARCHAR(96) DEFAULT '',
password	VARCHAR(96) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS session
(
id BIGSERIAL PRIMARY KEY,
user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
username	VARCHAR(64) NOT NULL UNIQUE,
session	VARCHAR(96) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS topics
(
id BIGSERIAL PRIMARY KEY,
title	VARCHAR(96) DEFAULT '',
body	TEXT DEFAULT '',
number_of_comments BIGINT NOT NULL,
number_of_likes BIGINT NOT NULL,
creator_id BIGINT NOT NULL REFERENCES users(id),
created	VARCHAR(96) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS topiclike
(
id BIGSERIAL PRIMARY KEY,
topic_id BIGINT NOT NULL REFERENCES topics(id),
user_id BIGINT NOT NULL REFERENCES users(id),
created	TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
id BIGSERIAL PRIMARY KEY,
topic_id BIGINT NOT NULL REFERENCES topics(id),
creator_id BIGINT NOT NULL REFERENCES users(id),
created	TIMESTAMP NOT NULL,
body	TEXT DEFAULT ''
);
